Client/Client/Models/UserIdentity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Client.Models
{
    public class UserIdentity
    {
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public string WorkAddress { get; set; }
    }
}

Client/Client/ViewModels/UserIdentityViewModel.cs
using Client.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Client.ViewModels
{
    public class UserIdentityViewModel
    {
        public UserIdentity Identity { get; set; }
    }
}

Client/Client/Controllers/HomeController.cs
using Client.Models;
using Client.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace Client.Controllers
{
    public class HomeController : Controller
    {
        HttpClient _client;

        /// <summary>
        /// ctor for home controller, init the http client
        /// </summary>
        public HomeController()
        {
            _client = new HttpClient();
            _client.BaseAddress = new Uri("http://localhost:39265/");
        }

        /// <summary>
        /// go to index view
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// go to main page with connected user by email
        /// </summary>
        public ActionResult Main(string email)
        {
            var result = _client.GetAsync($"api/Identity/GetUserIdentity?email={email}").Result;
            if (!result.IsSuccessStatusCode)
            {
                throw new Exception(result.Content.ReadAsStringAsync().Result);
            }

            string response = result.Content.ReadAsStringAsync().Result;
            var identity = JsonConvert.DeserializeObject<UserIdentity>(response);
            var viewModel = new UserIdentityViewModel
            {
                Identity = identity
            };

            return View(viewModel);
        }       

        /// <summary>
        /// go to login page
        /// </summary>
        public ActionResult Login()
        {
            return View();
        }

        /// <summary>
        /// go to register page
        /// </summary>
        public ActionResult Register()
        {
            return View();
        }

        /// <summary>
        /// go to about page
        /// </summary>
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        /// <summary>
        /// go to contact page
        /// </summary>
        public ActionResult Contact()
        {
            return View();
        }
    }
}

Client/Client/Controllers/IdentityController.cs
using Client.Models;
using Client.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace Client.Controllers
{
    public class IdentityController : Controller
    {
        HttpClient _client;
        public IdentityController()
        {
            _client = new HttpClient();
            _client.BaseAddress = new Uri("http://localhost:39265/");
        }
        
        /// <summary>
        /// Get identity info by email
        /// </summary>
        public ActionResult Info(string email)
        {
            var result = _client.GetAsync($"api/Identity/GetUserIdentity?email={email}").Result;
            if (!result.IsSuccessStatusCode)
            {
                throw new Exception(result.Content.ReadAsStringAsync().Result);
            }

            string response = result.Content.ReadAsStringAsync().Result;
            var identity = JsonConvert.DeserializeObject<UserIdentity>(response);

            var identityViewModel = new UserIdentityViewModel
            {
                Identity = identity
            };

            return View(identityViewModel);
        }

        /// <summary>
        /// edit identity details
        /// </summary>
        [HttpPost]
        public ActionResult Edit(UserIdentity identity)
        {
            try
            {
                string json = JsonConvert.SerializeObject(identity);
                var result = _client.PostAsync($"api/Identity/UpdateUserIdentity?userIdentity={identity}", new StringContent(json, System.Text.Encoding.UTF8, "application/json")).Result;
                if (!result.IsSuccessStatusCode)
                {
                    throw new Exception(result.Content.ReadAsStringAsync().Result);
                }
                return RedirectToAction("Main", "Home", routeValues: new { email = identity.Email });
            }
            catch
            {
                return View();
            }
        }
    }
}

Client/Client/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Client.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            return View("Login");
        }

        public ActionResult Login(string email, string password)
        {

        }
    }
}

Client/Client/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Client/Client/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
}
<h2>@ViewBag.Title.</h2>

<address>
    Sela Group<br />
    Ranana, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Sanad:</strong> <p>Phone: 0545454545</p> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Daisy:</strong> <p>Phone: 0545454545</p> <a href="mailto:Marketing@example.com">Daisy@example.com</a>
</address>

Client/Client/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <div class="index">
        <h1>InstaBook</h1>
        <p class="lead">Connecting People</p>
        <p class="btn btn-lg">@Html.ActionLink("Login", "Login", "Home") &raquo;</p>
        <p class="btn btn-lg">@Html.ActionLink("Register", "Register", "Home") &raquo;</p>
    </div>
</div>

Client/Client/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>
<p>Fill Login...</p>
<button class="btn">
    @Html.ActionLink("Login","Main","Home",
    routeValues: new { email = "rit@g.com"},
    htmlAttributes: null)
</button>

Client/Client/Views/Home/Main.cshtml
@model Client.ViewModels.UserIdentityViewModel
@{
    ViewBag.Title = "Main";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome, we miss you</h2>

<div class="identity">
    @Html.Partial("_Identity", Model.Identity);
</div>

Client/Client/Views/Home/Register.cshtml
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Register</h2>

Client/Client/Views/Shared/_Identity.cshtml
@model Client.Models.UserIdentity

<form>
    <div class="form-group">
        <label for="FullName">Full Name</label>
        <p>@Model.FirstName @Model.LastName</p>
    </div>
    <div class="form-group">
        <label for="age">Age</label>
        <p>@Model.Age</p>
    </div>
    <div class="form-group">
        <label for="address">Address</label>
        <p class="help">@Model.Address</p>
    </div>
    <div class="form-group">
        <label for="work">Work Address</label>
        <p>@Model.WorkAddress</p>
    </div>
</form>

<button class="btn">
    @Html.ActionLink("Edit", "Info", "Identity",
    routeValues: new {email = Model.Email},
    htmlAttributes: null)
</button>

Client/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar");
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Copyleft </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Client/Client/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("InstaBoook", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</div>